POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1yWCIsImlkIjoiNjZmODMwYjZkNWFmYjcxMzlmNzc2OTUyIiwiaWF0IjoxNzI3NTQxODg5fQ.R77uNx3SepVRDqreURFP1Dt-N0X5uQfOhalJ3e5N1Ek

{
    "title": "blogElbarto",
    "author": "elbarto",
    "url": "urlElbarto",
    "likes": 3
}